repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a5'  # Use the sha / tag you want to point at
    hooks:
    - id: pylint
      exclude: setup.py
      args:
        -  --disable=E0401
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-yaml
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
    - id: mixed-line-ending
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
    - id: pyupgrade
      args: ["--py38-plus"]
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        additional_dependencies:
            - toml
