[project]
name = "pyrdp"
version = "0.1.6"
description = "Simple Rammer-Douglas-Peuker algorithm implementation."
authors = [{ name = "Florian Stasse", email = "f.stasse@skipperndt.com" }]
dependencies = ["numpy>=1.23.4"]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
Repository = "https://github.com/FlorianStasse/rdp-algo/"

[dependency-groups]
dev = [
    "pytest>=7.3.1",
    "ruff>=0.16.10",
]

[build-system]
requires = ["uv_build>=0.12.18,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[tool.ruff.lint]
extend-select = ["I", "UP"]
